name: Build and Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Setup vcpkg and install Vulkan
      run: |
        git clone https://github.com/microsoft/vcpkg.git --depth 1
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install vulkan-headers vulkan-loader:x64-windows

    - name: Configure (Debug)
      run: |
        $tc = Join-Path $env:GITHUB_WORKSPACE "vcpkg\scripts\buildsystems\vcpkg.cmake"
        cmake --preset debug -DCMAKE_TOOLCHAIN_FILE="$tc"

    - name: Build (Debug)
      run: cmake --build --preset build-debug

    - name: Test (Debug)
      run: ctest --preset test-debug

    - name: Configure (Release)
      run: |
        $tc = Join-Path $env:GITHUB_WORKSPACE "vcpkg\scripts\buildsystems\vcpkg.cmake"
        cmake --preset release -DCMAKE_TOOLCHAIN_FILE="$tc"

    - name: Build (Release)
      run: cmake --build --preset build-release

    - name: Test (Release)
      run: ctest --preset test-release
